units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # M2 Screw Inserts
  screwRadius: 1.50
  standoffRadius: 3
  # Footprints
  rp2040zero_x: 18
  rp2040zero_y: 23.5
  usb_x: 8.94
  usb_y: 7.35
  fpc_x: 5
  fpc_y: 11
points:
  zones:
    matrix:
      anchor:
        shift: [30, -80]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          key:
            splay: 5
            column_net: lGP9
            mirror.column_net: rGP9
        ring:
          key:
            stagger: 0.33ky
            splay: -3
            spread: 1kx + 2
            column_net: lGP10
            mirror.column_net: rGP10
        middle:
          key:
            stagger: 0.33ky
            splay: -2
            spread: 1kx + 1
            column_net: lGP11
            mirror.column_net: rGP11
        index:
          key:
            stagger: -0.45ky
            splay: -2
            spread: 1kx + 0.2
            column_net: lGP12
            mirror.column_net: rGP12
      rows:
        bottom:
          row_net: lGP27
          mirror.row_net: rGP27
        middle:
          row_net: lGP26
          mirror.row_net: rGP26
        top:
          row_net: lGP15
          mirror.row_net: rGP15
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_index_bottom
        shift: [.9kx, -1.2ky]
      columns:
        middle:
          key:
            width: 1.5kx
            splay: -20
            stagger: -0.2ky
            column_net: lGP11
            mirror.column_net: rGP11
        outer:
          key:
            width: 1.5kx
            spread: 1ky+1
            column_net: lGP12
            mirror.column_net: rGP12
      rows:
        cluster:
          row_net: lGP28
          mirror.column_net: rGP28
        top:
          row_net: lGP29
          mirror.column_net: rGP29
    mcu:
      anchor:
        ref: matrix_middle_top
        shift: [2.3kx, -.5ky]
      key:
        width: rp2040zero_x
        height: rp2040zero_y
    cirque:
      anchor:
        ref: mcu
        shift: [.5kx, -1.5ky]
      key:
        width: rp2040zero_x
        height: rp2040zero_y
    fpc:
      anchor:
        ref: mcu
        shift: [0.5kx, -1.5ky]
      key:
        width: fpc_x
        height: fpc_y
    usb:
      anchor:
        ref: matrix_middle_top
        shift: [1.1kx, .32ky]
      key:
        width: usb_x
        height: usb_y
    holeRingTop:
      anchor:
        ref: [matrix_ring_top]
        shift: [0.33px, 0.56py]
    holeRingBottom:
      anchor:
        ref: [matrix_ring_bottom]
        shift: [-0.35kx, -0.7ky]
    holeOuterThumbs:
      anchor:
        ref: [matrix_index_bottom]
        shift: [0.6kx, -0.45ky]
  mirror: &mirror
    ref: matrix_index_top
    distance: 120
outlines:
  keys:
    - what: rectangle
      where: /matrix|thumb/
      size: [kx-0.5, ky-0.5]
  boardLeft:
    - what: polygon
      operation: stack
      fillet: 1
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: usb
          shift: [usb_x/2, usb_y/2]
        - ref: mcu
          shift: [-rp2040zero_x/2, rp2040zero_y/2+2]
        - ref: mcu
          shift: [rp2040zero_x/2+4, rp2040zero_y/2+2]
        - ref: thumbs_outer_top
          shift: [-0.32px, 0.5py]
        - ref: thumbs_outer_top
          shift: [0.5px, 0.5py]
        - ref: thumbs_outer_cluster
          shift: [0.5px, 0.5py]
        - ref: thumbs_outer_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_middle_cluster
          shift: [-0.5px, -0.5py]
        - ref: thumbs_middle_cluster
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px, -0.5py]
  boardRight:
    - what: polygon
      operation: stack
      fillet: 1
      points:
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: mirror_usb
          shift: [usb_x/2, usb_y/2]
        - ref: mirror_mcu
          shift: [-rp2040zero_x/2, rp2040zero_y/2+2]
        - ref: mirror_mcu
          shift: [rp2040zero_x/2+4, rp2040zero_y/2+2]
        - ref: mirror_thumbs_outer_top
          shift: [-0.32px, 0.5py]
        - ref: mirror_thumbs_outer_top
          shift: [0.5px, 0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [0.5px, 0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [0.5px, -0.5py]
        - ref: mirror_thumbs_middle_cluster
          shift: [-0.5px, -0.5py]
        - ref: mirror_thumbs_middle_cluster
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px, -0.5py]
  board:
    - boardLeft
    - boardRight
  _mcu:
    - what: rectangle
      where: /mcu/
      size: [rp2040zero_x, rp2040zero_y]
  _fpc:
    - what: rectangle
      where: /fpc/
      size: [fpc_x, fpc_y]
  _cirque:
    - what: circle
      where: /cirque/
      radius: 20
  _usb:
    - what: rectangle
      where: /usb/
      size: [usb_x, usb_y]
  _mountingLeft:
    - what: circle
      where: /^hole/
      radius: screwRadius
  _mountingRight:
    - what: circle
      where: /^mirror_hole/
      radius: screwRadius
  _standoffLeft:
    - what: circle
      where: /^hole/
      radius: standoffRadius
  _standoffRight:
    - what: circle
      where: /^hole/
      radius: standoffRadius
  combo:
    - ^boardLeft
    - ^boardRight
    - ^keys
    - ^_mcu
    - ^_fpc
    - ^_cirque
    - ^_usb
    - ^_standoffLeft
    - ^_standoffRight
    - ^_mountingLeft
    - ^_mountingRight
pcbs:
  mushi:
    outlines:
      main:
        outline: board
    footprints:
      chocHotswapLeft:
        what: choc
        where: /^(thumb|matrix)/
        params:
          keycaps: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diodeLeft:
        what: diode
        where: /^(thumb|matrix)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      chocHotswapRight:
        what: choc
        where: /^mirror_(thumb|matrix)/
        params:
          keycaps: true
          hotswap: true
          from: "{{mirror.column_net}}"
          to: "{{mirror.colrow}}"
      diodeRight:
        what: diode
        where: /^mirror_(thumb|matrix)/
        params:
          from: "{{mirror.colrow}}"
          to: "{{mirror.row_net}}"
        adjust:
          shift: [0, -5]
      mcuLeft:
        what: rp2040zero
        where: mcu
        adjust:
          shift: [-rp2040zero_x / 2, -rp2040zero_y / 2]
        params:
          reverse: true
          P5V: lP5V
          GND: lGND
          P3V3: lP3V3
          GP29: lGP29
          GP28: lGP28
          GP27: lGP27
          GP26: lGP26
          GP15: lGP15
          GP14: lGP14
          GP13: lGP13
          GP12: lGP12
          GP11: lGP11
          GP10: lGP10
          GP9: lGP9
          GP8: lGP8
          GP7: lGP7
          GP6: lGP6
          GP5: lGP5
          GP4: lGP4
          GP3: lGP3
          GP2: lGP2
          GP1: lGP1
          GP0: lGP0
      mcuRight:
        what: rp2040zero
        where: mirror_mcu
        adjust:
          shift: [rp2040zero_x / 2 + 2.29, -rp2040zero_y / 2]
        params:
          P5V: rP5V
          GND: rGND
          P3V3: rP3V3
          GP29: rGP29
          GP28: rGP28
          GP27: rGP27
          GP26: rGP26
          GP15: rGP15
          GP14: rGP14
          GP13: rGP13
          GP12: rGP12
          GP11: rGP11
          GP10: rGP10
          GP9: rGP9
          GP8: rGP8
          GP7: rGP7
          GP6: rGP6
          GP5: rGP5
          GP4: rGP4
          GP3: rGP3
          GP2: rGP2
          GP1: rGP1
          GP0: rGP0
      holes:
        what: mountinghole
        where: /hole/
